import type { PlayerProfile } from "@/types";

// Demo profiles for testing and demonstration
export const DEMO_PROFILES: Record<string, Partial<PlayerProfile>> = {
  "Blue Chip D1 (MLS NEXT)": {
    firstName: "Alex",
    lastName: "Romero",
    gender: "Male",
    position: "CM",
    gradYear: 2026,
    state: "CA",
    experienceLevel: "elite",
    hasVideo: true,
    coachesContacted: 25,
    responsesReceived: 8,
    offersReceived: 1,
    gpa: 3.6,
    testScore: "1250 SAT",
    athleticProfile: {
      fortyYardDash: "4.7s",
      mileTime: "5:20",
      beepTestLevel: 55,
    },
    seasons: [
      {
        year: 2024,
        teamName: "LA Galaxy Academy",
        league: "MLS_NEXT",
        gamesPlayed: 25,
        goals: 8,
        assists: 12,
      },
    ],
    events: [
      {
        name: "Jefferson Cup",
        type: "showcase",
        date: "2024-03-15",
        location: "Richmond, VA",
      },
    ],
  },

  "Solid Recruit (ECNL)": {
    firstName: "Liam",
    lastName: "Smith",
    gender: "Male",
    position: "CB",
    gradYear: 2026,
    state: "TX",
    experienceLevel: "high",
    hasVideo: true,
    coachesContacted: 15,
    responsesReceived: 2,
    offersReceived: 0,
    gpa: 3.2,
    testScore: "1100 SAT",
    athleticProfile: {
      fortyYardDash: "5.0s",
      mileTime: "5:45",
      beepTestLevel: 48,
    },
    seasons: [
      {
        year: 2024,
        teamName: "Mustang SC",
        league: "ECNL",
        gamesPlayed: 22,
        goals: 3,
        assists: 1,
      },
    ],
    events: [
      {
        name: "Dallas Cup",
        type: "showcase",
        date: "2024-04-01",
        location: "Dallas, TX",
      },
    ],
  },

  "High Academic D3 (ECNL RL)": {
    firstName: "Emma",
    lastName: "Davis",
    gender: "Female",
    position: "CDM",
    gradYear: 2025,
    state: "WA",
    experienceLevel: "high",
    hasVideo: true,
    coachesContacted: 40,
    responsesReceived: 12,
    offersReceived: 2,
    gpa: 4.0,
    testScore: "1450 SAT",
    athleticProfile: {
      fortyYardDash: "5.3s",
      mileTime: "6:00",
      beepTestLevel: 45,
    },
    seasons: [
      {
        year: 2024,
        teamName: "Crossfire",
        league: "ECNL_RL",
        gamesPlayed: 24,
        goals: 2,
        assists: 6,
      },
    ],
    events: [
      {
        name: "PDA ID Camp",
        type: "id_camp",
        date: "2024-07-10",
        location: "NJ",
      },
    ],
  },

  "Late Bloomer (NPL)": {
    firstName: "Marcus",
    lastName: "Johnson",
    gender: "Male",
    position: "ST",
    gradYear: 2025,
    state: "FL",
    experienceLevel: "moderate",
    hasVideo: false,
    coachesContacted: 0,
    responsesReceived: 0,
    offersReceived: 0,
    gpa: 3.0,
    athleticProfile: {
      fortyYardDash: "4.9s",
      mileTime: "5:50",
      beepTestLevel: 42,
    },
    seasons: [
      {
        year: 2024,
        teamName: "Florida Elite",
        league: "NPL",
        gamesPlayed: 20,
        goals: 15,
        assists: 5,
      },
    ],
    events: [],
  },

  "Girls Academy Prospect": {
    firstName: "Sophia",
    lastName: "Martinez",
    gender: "Female",
    position: "LW",
    gradYear: 2027,
    state: "NY",
    experienceLevel: "elite",
    hasVideo: true,
    coachesContacted: 5,
    responsesReceived: 1,
    offersReceived: 0,
    gpa: 3.8,
    athleticProfile: {
      fortyYardDash: "5.0s",
      mileTime: "5:40",
      beepTestLevel: 50,
    },
    seasons: [
      {
        year: 2024,
        teamName: "SoCal Blues",
        league: "Girls_Academy",
        gamesPlayed: 22,
        goals: 12,
        assists: 8,
      },
    ],
    events: [
      {
        name: "ECNL National Playoffs",
        type: "tournament",
        date: "2024-06-20",
        location: "San Diego, CA",
      },
    ],
  },

  "Goalkeeper Prospect": {
    firstName: "Tyler",
    lastName: "Anderson",
    gender: "Male",
    position: "GK",
    gradYear: 2026,
    state: "OH",
    height: "6'2\"",
    experienceLevel: "high",
    hasVideo: true,
    coachesContacted: 20,
    responsesReceived: 5,
    offersReceived: 0,
    gpa: 3.4,
    athleticProfile: {
      fortyYardDash: "5.2s",
    },
    seasons: [
      {
        year: 2024,
        teamName: "Columbus Crew Academy",
        league: "MLS_NEXT",
        gamesPlayed: 18,
        goals: 0,
        assists: 0,
        cleanSheets: 10,
      },
    ],
    events: [
      {
        name: "IMG Academy GK Camp",
        type: "training",
        date: "2024-07-15",
        location: "Bradenton, FL",
      },
    ],
  },

  "High School Only": {
    firstName: "Jake",
    lastName: "Williams",
    gender: "Male",
    position: "RB",
    gradYear: 2026,
    state: "MI",
    experienceLevel: "moderate",
    hasVideo: false,
    coachesContacted: 0,
    responsesReceived: 0,
    offersReceived: 0,
    gpa: 3.5,
    seasons: [
      {
        year: 2024,
        teamName: "Ann Arbor HS",
        league: "High_School",
        gamesPlayed: 18,
        goals: 2,
        assists: 8,
      },
    ],
    events: [],
  },

  "NAIA Target": {
    firstName: "Carlos",
    lastName: "Hernandez",
    gender: "Male",
    position: "CAM",
    gradYear: 2025,
    state: "AZ",
    citizenship: "US",
    experienceLevel: "moderate",
    hasVideo: true,
    coachesContacted: 30,
    responsesReceived: 8,
    offersReceived: 1,
    gpa: 2.8,
    athleticProfile: {
      fortyYardDash: "5.1s",
      mileTime: "6:10",
      beepTestLevel: 40,
    },
    seasons: [
      {
        year: 2024,
        teamName: "Phoenix Rising Academy",
        league: "USL_Academy",
        gamesPlayed: 16,
        goals: 6,
        assists: 4,
      },
    ],
    events: [
      {
        name: "NAIA ID Camp",
        type: "id_camp",
        date: "2024-06-01",
        location: "Phoenix, AZ",
      },
    ],
  },

  "Junior College Path": {
    firstName: "DeShawn",
    lastName: "Thompson",
    gender: "Male",
    position: "CDM",
    gradYear: 2025,
    state: "GA",
    experienceLevel: "developing",
    hasVideo: false,
    coachesContacted: 10,
    responsesReceived: 3,
    offersReceived: 0,
    gpa: 2.2,
    seasons: [
      {
        year: 2024,
        teamName: "Atlanta FC",
        league: "Club_Local",
        gamesPlayed: 20,
        goals: 1,
        assists: 3,
      },
    ],
    events: [],
  },

  "Invisible Talent": {
    firstName: "Ryan",
    lastName: "Chen",
    gender: "Male",
    position: "CM",
    gradYear: 2026,
    state: "NJ",
    experienceLevel: "high",
    hasVideo: false,
    coachesContacted: 0,
    responsesReceived: 0,
    offersReceived: 0,
    gpa: 3.7,
    athleticProfile: {
      fortyYardDash: "4.9s",
      mileTime: "5:30",
      beepTestLevel: 52,
    },
    seasons: [
      {
        year: 2024,
        teamName: "PDA",
        league: "ECNL",
        gamesPlayed: 24,
        goals: 5,
        assists: 10,
      },
    ],
    events: [],
  },
};
